input_features:
  - name: image_id
    type: image
    preprocessing:
      height: 224    
      width: 224
      num_channels: 3
    encoder:
      type: stacked_cnn
      conv_layers:
        - num_filters: 32
          filter_size: 3
          stride: 1
          padding: same
          pool_size: 2
          pool_stride: 2
        - num_filters: 64
          filter_size: 3
          stride: 1
          padding: same
          pool_size: 2
          pool_stride: 2
      dropout: 0.2

output_features:
  - name: label
    type: category

training:
  epochs: 50

preprocessing:
  split:
    type: fixed
    column: split
